"""empty message

Revision ID: 929889f0ec01
Revises: ba9ed82521e9
Create Date: 2020-05-05 08:15:04.420878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '929889f0ec01'
down_revision = 'ba9ed82521e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('currency_value', sa.Integer(), nullable=True))
    op.drop_column('currency', 'currancy_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('currancy_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('currency', 'currency_value')
    # ### end Alembic commands ###
