"""empty message

Revision ID: ba9ed82521e9
Revises: f4e4c7f92be6
Create Date: 2020-05-05 06:34:43.869134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9ed82521e9'
down_revision = 'f4e4c7f92be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(length=100), nullable=True),
    sa.Column('currancy_value', sa.Integer(), nullable=True),
    sa.Column('currency_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
