"""empty message

Revision ID: bd85ae7283fc
Revises: ce06d80fbdb6
Create Date: 2020-05-05 11:28:46.701828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd85ae7283fc'
down_revision = 'ce06d80fbdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('currency_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'currency_value')
    # ### end Alembic commands ###
